<a href="https://colab.research.google.com/github/Sinchiguano/ai2023_2/blob/main/NumPy_Exercises_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [ ]:
# Import numpy as np and see the version

# your code here
pass

In [ ]:
# Create a 1D array of numbers from 0 to 9
# your code here
pass

In [ ]:
# Print the number 8 from the array below:
# arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
pass

In [1]:
# Print the numbers [3, 4, 5] from the array below:
# arr = np.array([1,2,3,4,5,6,7])
pass

In [7]:
# Print the last 4 numbers from the array below:
# arr = np.array([1,2,3,4,5,6,7])
pass

In [ ]:
# Create a 3×3 numpy array of all True’s
# your code here
pass

In [11]:
# Extract all odd numbers from arr
# your code here
pass

In [12]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
pass


In [29]:
# Reverse a vector (first element becomes last)
pass

In [30]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
pass

In [8]:
# Replace all odd numbers in arr with -1
# your code here
pass

In [9]:
# Create an array of type float
pass

In [31]:
# Convert a 1D array to a 2D array with 2 rows
# your code here
pass

In [32]:
# Stack arrays a and b vertically
# your code here
pass

In [33]:
# Stack the arrays a and b horizontally.
# your code here
pass

In [34]:
# Get all items between 5 and 10 from array tmp.
# your code here
import numpy as np
tmp = np.arange(15)
# pass

In [ ]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here
import numpy as np

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)


5

In [ ]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


arr = np.arange(9).reshape(3,3)
print(arr)
# your code here
pass


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]